### ISSUE TITLE
Thoughtseize card shows up in HOU (and MPS_HOU)

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#113]
With #112, cards are compared against the mtgs spoiler gallery.
So the manual deletion of cards is hopefully less needed.

For `Thougtseize`, which is a Masterpiece for HOU, it doesn't seem to work.
The card is by fault in their hou spoiler rss, but correctly does not show up in their [gallery](http://www.mtgsalvation.com/spoilers/183-hour-of-devastation).
Still it isn't removed... so it ends up twice in our spoiler.xml:
HOU --> https://github.com/Cockatrice/Magic-Spoiler/blob/0cb2bd0431dba9a70ff96727da50bc7b7e1d955b/spoiler.xml#L2162
MPS_HOU --> https://github.com/Cockatrice/Magic-Spoiler/blob/0cb2bd0431dba9a70ff96727da50bc7b7e1d955b/spoiler.xml#L2687

See https://github.com/Cockatrice/Magic-Spoiler/commit/0cb2bd0431dba9a70ff96727da50bc7b7e1d955b for the pushed change to files branch.

---

**Update:**
Tried to fix it with temporary adding it back to card deletioins: https://github.com/Cockatrice/Magic-Spoiler/commit/53aeabd448fd81154beca98b1a344cb26a1b8e5a

Didn't work out though and ended up deleting both in spoiler.xml!?
--> https://travis-ci.org/Cockatrice/Magic-Spoiler/builds/251730300 (btw new record: 53s :D )

For the other cards removed from cards_deletions in https://github.com/Cockatrice/Magic-Spoiler/commit/529a4da3d961e0a0ef1b4bc9af0d8fb4dcda282 it seems to work fine.
But they also just appear once. So there might be a problem here if cards appear in several sets!
Did it work before correctly? Or we just didn't spot that?

<br>

**Edit2:**
I could also not find this printed line in the travis log:
https://github.com/Cockatrice/Magic-Spoiler/pull/112/files#diff-56330639fe863365e37a8175e77fbc27R41
Maybe related?

**Comment by ZeldaZach** [comment]
We will be fixing MTGJSON today, sorry for the issues

**Comment by tooomm** [comment]
This is not related to mtgjson in any way @ZeldaZach... ;)

**Comment by tooomm** [comment]
Probably not valid anymore since script got rewritten
