### ISSUE TITLE
travis: auto-remove sets found in mtgjson (output files, set_info, cards_*)

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#126]
In extension to https://github.com/Cockatrice/Magic-Spoiler/pull/84 we might also want to remove the set info from https://github.com/Cockatrice/Magic-Spoiler/blob/master/set_info.yml in case mtgjson has it.

Same for https://github.com/Cockatrice/Magic-Spoiler/blob/master/cards_manual.yml additions regarding that set.
In theory we could compare the names from card corrections and card deletion file too!

We just want travis to open a pr for that maybe, instead a push to master branch though.

**Comment by dev-id** [comment]
Not sure if this is feasible. I'd have to see an example of travis submitting a PR to master from a build.

We could theoretically have it write to yet another branch with those kinds of changes.

**Comment by tooomm** [comment]
The idea with the pr was that it's just two clicks for us to get it in and clean everything up:
- double check changes and verify the file deletions
- 1st click: merge pr
- 2nd click: delete branch

**Comment by tooomm** [comment]
The GitHub API can be used to create a PR: https://developer.github.com/v3/pulls/#create-a-pull-request

For the "output spoiler files" it would need to be a pr against `files`.
For the "set_info" and/or "cards_*" changes  it would be against `master`.

The easier and more important one is the first one.
We don't have to use the corrections, delete or manual files too much recently, and with no cards matching their names they do nothing anyway. (besides cards_manual, and only if set_info still contains the outdated set)
