### ISSUE TITLE
Link style information in xml's

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#128]
If you open the attached files from a release (e.g. HOU: https://github.com/Cockatrice/Magic-Spoiler/releases/tag/v0.170702.001) in Firefox, the files gets opened but not displayed correctly.

There is also an hint on top, that `This XML file does not appear to have any style information associated with it. The document tree is shown below.`
Chrome just downloads instead displaying xml's...

We might have to add a scheme or something?

**Comment by dev-id** [comment]
Looks like there's no standard for embedding style in xml: https://www.w3.org/Style/styling-XML.en.html

Adding external stylesheet probably won't work with github hosting

**Comment by tooomm** [comment]
No longer valid, might happened to be a Firefox bug.
Firefox now also wants to download xml files once you open them!

**Comment by tooomm** [comment]
What me got thinking though was the different files header compared to the [`tokens.xml`](https://github.com/Cockatrice/Magic-Token/blob/master/tokens.xml):

```
<?xml version="1.0" encoding="UTF-8"?>
<cockatrice_carddatabase version="3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/Cockatrice/Cockatrice/master/doc/cards.xsd">
```

[Our xml's](https://github.com/Cockatrice/Magic-Spoiler/tree/files):
```
<?xml version="1.0" ?><cockatrice_carddatabase version="3"> 
```

We verify the xml's in travis, but don't include scheme information, nor character encoding in the output files.

Edit: it looks like we add char encoding info, but it never appears in the files?!
--> https://github.com/Cockatrice/Magic-Spoiler/blob/master/spoilers.py#L552
Readded it in #277

**Comment by tooomm** [comment]
Addressed by https://github.com/Cockatrice/Magic-Spoiler/pull/286 and #251
