### ISSUE TITLE
prevent date-only changes to spoiler files

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#129]
Just let travis push changes (especially date-only updates!) when there is a change to the file besides the date.

It's confusing if the date updates, but not the content. A reddit user might try to update/override the file over and over again without seeing any actual changes/new content!
Also messes around with the activity feed in gitter during off-season, as well as repo activity on github in general!

Maybe we can check if some of the `setcode.xml` files are changed as well.
Because the `spoiler.xml` file reflects that changes, plus the date change. Without a change in the single e.g. `HOU.xml` (or any other single set xml or json file), there should never be a need for a change in `spoiler.xml`.
Or check for changes in that particular [line](https://github.com/Cockatrice/Magic-Spoiler/blob/files/spoiler.xml#L3) for example, since that line reference is always the same...

There might be an even smarter way of handling this?!

**Comment by dev-id** [comment]
Fixed by #141 (and subsequent commits)

**Comment by tooomm** [comment]
Reopening because date-only changes get still commited as long as there are other changes applied to different files in the same run, for example: https://github.com/Cockatrice/Magic-Spoiler/commit/f713027dcbe74cf126e77d0441710a97a5fdc7d1 or https://github.com/Cockatrice/Magic-Spoiler/commit/1d6670a74e8339c8ac5ac449da38afc3be00fbe9

The `spoiler.xml` file should not be touched in such cases to falsely imply a content update.

**Comment by tooomm** [comment]
Currently, on every CI run, there are always files deployed again, e.g. https://github.com/Cockatrice/Magic-Spoiler/commit/ce6ffe96d69021e2ee864ee3edfbf37b977a8c34.

The reason is still the constantly changed date in the file.
We had a solution in place to filter out "date-only changes", but with the move to GitHub Actions, this logic got not preserved.
I did some digging and found it again: https://github.com/Cockatrice/Magic-Spoiler/pull/258/files#diff-0a42ee357984cc5054a8c64b6fefb8d853d8daab34ecb44817b9e1e7f26dbe25L63-L81

Only individual set files (+ the combined spoiler file), which receive actual content updates need to be deployed.
Otherwise users end up getting notifications in the client about new spoiler data basically every time they open up the client, but there are no new cards or updated data...

**Comment by ebbit1q** [comment]
this should be handled by the python code, not the ci
