### ISSUE TITLE
travis: prettify + summarize log (collapsable/foldable parts)

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#149]
Travis CI automatically folds sections and hides them.
Add custom folds to travis log for spoiler.xml print etc. to keep all log smaller, tidier and at the end more useful when you search for something!

Notes:
https://blog.travis-ci.com/2013-05-22-improving-build-visibility-log-folds/
http://enricostano.github.io/articles/dealing-with-travis-ci-console-output/
https://github.com/travis-ci/travis-ci --> issue 2285
https://github.com/travis-ci/docs-travis-ci-com --> issue 949
https://www.koszek.com/blog/2016/07/25/dealing-with-large-jobs-on-travis/
https://github.com/macbre/travis-fold (see example)

---

First preview in https://github.com/Cockatrice/Magic-Spoiler/commit/61bcca698e0bcac7ee69e7951b22a759fac02e7c @ https://github.com/Cockatrice/Magic-Spoiler/tree/tooomm-fold_script_output
--> result: https://travis-ci.org/Cockatrice/Magic-Spoiler/builds/277294118#L483

Due to the monolithic construction right now we can't just fold script parts thematically like "scraper statistics/set overview", "xml output dump" or "errors".
Once the script is split in it's parts, each one could see its own folded section with a headline about what's going on (see https://github.com/Cockatrice/Magic-Spoiler/issues/95)

**Comment by dev-id** [comment]
So if I'm understanding, we need to split `doCompile` into `doBuild`, `doXML`, `doJSON` and `doErrors`?

**Comment by tooomm** [comment]
That would allow to wrap each of this parts into the folding code from travis at least.
If that's the ideal way to go for all of those I don't know yet.
Also depends on how the future modularization will look like.

Interacting with the bash commands for travis right out of the python script might be tricky, but possible.

**Comment by tooomm** [comment]
no longer valid
