### ISSUE TITLE
Glacial Fortress missing

### ISSUE THREAD

**Issue by davisbnag** [Cockatrice/Magic-Spoiler#163]
Glacial Fortress is missing from:

https://raw.githubusercontent.com/Cockatrice/Magic-Spoiler/files/XLN.xml

**Comment by Cheldra** [comment]
has been patched in (https://github.com/Cockatrice/Magic-Spoiler/commit/4799e9260001c92b6e84d21ecd1159a16a3fc00d), will be in the xml next time it updates

**Comment by tooomm** [comment]
It is already updated @Cheldra :P

Thanks for the report and help @davisbnag
