### ISSUE TITLE
pic urls from scryfall has appended key

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#196]
See https://github.com/Cockatrice/Magic-Spoiler/blob/360b2004321e505c4042504d2a33dda3b28ef76c/RIX.xml#L13

**Comment by ZeldaZach** [comment]
This "key" is just an arbitrary note to clear the local cache. It has no relevance to the actual image

**Comment by tooomm** [comment]
That number is actually included into their api response. Maybe some sort of tracking?

Would it be reasonable to strip/discard that appendix?
![chupacabra](https://user-images.githubusercontent.com/9874850/34685504-d8dbea2a-f4a8-11e7-958b-5f4c3e639684.png)

https://api.scryfall.com/cards/rix/82

**Comment by tooomm** [comment]
Is there a benefit in having/keeping these randomly changing (?) numbers?
Does Cockatrice recognize those at all? I don't think it'll trigger a fresh image download.

Currently, it only leads to updates to the spoiler file without changing its content:
https://github.com/Cockatrice/Magic-Spoiler/commit/165d914f42bd23651a97a7ad66b9a72a255a2f3e#diff-ffd8e1a9d03f7f78a529e9e6c9ca5127
or https://github.com/Cockatrice/Magic-Spoiler/commit/e6fb695c1b93a030d95c9fed382d8ed1e90c152c#diff-ffd8e1a9d03f7f78a529e9e6c9ca5127
So users see a pop up with a refreshed date, but nothing changed.

Would it be safe to remove them?

**Comment by tooomm** [comment]
New image links with uuid don't have that any longer.

Actually, the appendix was removed from the URL in the script at one point:
https://github.com/Cockatrice/Magic-Spoiler/commit/69fac381f9da185876292268ab4d97fc9e69b425#diff-f9b2f278fa10b12db9edf49aefbb8dd890f71151e9f2d61670aa58f44bf3386aR166
https://github.com/Cockatrice/Magic-Spoiler/commit/c4764f3c17788cda05b8e1e0f2db894ffb9eade8#diff-f9b2f278fa10b12db9edf49aefbb8dd890f71151e9f2d61670aa58f44bf3386aL172
