### ISSUE TITLE
Improve Travis PR Functionality

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Magic-Spoiler#20]
If a user makes a change via GitHub and files a PR, Travis will run but they cannot see the changes in XML. If Travis is running via PR, it should dump XML to log.

With #19 all executions will dump XML to log, which is sub-optimal for non-PR.

**Comment by tooomm** [comment]
When I read about the xml dump to travis on Gitter I had the same restriction in mind.

**Comment by dev-id** [comment]
`dumpXML` now defaults to False, Travis sets it to true when it runs by appending `dumpXML=True` to the command line parameter

https://github.com/Cockatrice/Magic-Spoiler/commit/5d48d567c37cd63ac1e8f94b05918b3354af0732
https://travis-ci.org/Cockatrice/Magic-Spoiler/builds/245018031#L374

**Comment by tooomm** [comment]
So we never dump xml, except on all travis runs?

**Comment by dev-id** [comment]
>So we never dump xml, except on all travis runs?

All the `presets` (https://github.com/Cockatrice/Magic-Spoiler/blob/eba81f48d757f99fa840485b01815308b1920b5e/main.py#L9-L22) can be modified at runtime from the command line.

Travis now runs `python main.py dumpXML=True` https://github.com/Cockatrice/Magic-Spoiler/blob/master/deploy.sh#L8

I tried to handle a few different ways of passing parameters, but this is currently undocumented.

`--parameter=newvalue` or `parameter=newvalue` are both valid. `T`,`t`,`true`, and `True` all evaluate to `True` and similar for `False`.

**Comment by tooomm** [comment]
>All the presets (https://github.com/Cockatrice/Magic-Spoiler/blob/eba81f48d757f99fa840485b01815308b1920b5e/main.py#L9-L22) can be modified at runtime from the command line.

The script settings could be in a separate config file, so that a random user doesn't have to touch the script at all!
<br>

>Travis now runs python main.py dumpXML=True https://github.com/Cockatrice/Magic-Spoiler/blob/master/deploy.sh#L8

`deploy.sh` is just run by travis https://github.com/Cockatrice/Magic-Spoiler/blob/master/.travis.yml#L4
So on a manual local run it'll default to false if I understand correctly 👍
