### ISSUE TITLE
Prevent Travis to run on changes to .md files etc.

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#21]
If we change the README.md or any other *.md file Travis shouldn't run at all.
Not on Branch, not on PR and not on master.

**Comment by dev-id** [comment]
Reading discussion @ https://github.com/travis-ci/travis-ci/issues/6301 this is not possible currently.

Contributors will need to add `[skip ci]` or `[ci skip]` to their commit messages.

**Comment by tooomm** [comment]
Yes exactly, that's the workaround for now!

<br>

Edit: first try with an unofficial automated workaround in https://github.com/Cockatrice/Magic-Spoiler/pull/67

**Comment by tooomm** [comment]
addressed
