### ISSUE TITLE
Switch to mtgjson v4

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#225]
The old mtgjson file we use doesn't get updates anymore.
Because of that we can't drop existing sets automatically anymore and currently UMA etc. will stay in the spoiler file even when they are officially released on scryfall or gatherer.
Also our AllCards.json file isn't compatible with v4 anymore.

Is it as easy as exchanging the link @dev-id ?
Or do we need to adjust parsing since several fields changed in v4?

I think we only use set name and/or set code for comparison and dropping sets?
But on the other hand we integrate with the downloaded AllCards.json, too...

Maybe we can take `baseSetSize` from mtgjson instead having to fill out the `size` value in set_info.yml for every set for example.

**Comment by dev-id** [comment]
It appears that mtgjson v4 is not backwards compatible, we will need to adjust our _output_ fields to continue being compatible. Most of the changes between V3 and V4 are listed here: https://mtgjson.com/changelog.html

**Comment by tooomm** [comment]
>XML Stats for RNA
Total cards: 268

See: https://travis-ci.org/Cockatrice/Magic-Spoiler/jobs/481094443#L486-L487

<br>
Idea/note:

With the new `baseSetSize` (or `totalSetSize`) in v4 we could indicate if it's mostly spoiled already:
>XML Stats for RNA
Total cards: 268/259

**Comment by tooomm** [comment]
Also, I realized that already released sets available in mtgjson no longer get automatically discarded from the spoiler file!
