### ISSUE TITLE
Remove the Joke Cards from Spoilers

### ISSUE THREAD

**Issue by jonschoning** [Cockatrice/Magic-Spoiler#247]
I don't need or want "Hey Macarena!" in the card set - thank you

**Comment by tooomm** [comment]
The spoiler file is entirely sourced from scryfall.
Unfortunatelly, they use this "funny" names for cards which are not yet available with an english card art and the name is not officially translated yet.
For your example "Hey Macarena!" (https://scryfall.com/card/eld/106/hey-macarena!) all the card information and what it does is already available. That's important information for brewers even though the name is not fixed yet.

The important part about spoilers are the upcoming cards and their effects, not so much their names. Also, it's just a placeholder until the official name is known. The cards get then updated automatically for you.

Workaround: Setup a card filter `AND NOT Name "` to hide them

**Comment by jonschoning** [comment]
Ok thanks for the explanation
