### ISSUE TITLE
JSON output files are not v5 format

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#262]
We use an older MTGJSON format still.

**Comment by ebbit1q** [comment]
the json files serve no other purpose but to validate the xmls, they aren't used anywhere, we should rather consider not including them in deployments at all

**Comment by tooomm** [comment]
Reopening, due to https://github.com/Cockatrice/Magic-Spoiler/issues/294#issuecomment-1447513268

Aim:
> (...) to remove the json files without triggering it we should stop the json files being different from triggering a deploy in the python script.

**Comment by ebbit1q** [comment]
we should simply remove these from the script instead of ignoring them

**Comment by tooomm** [comment]
> we should simply remove these from the script instead of ignoring them

You mean delete them by the script?

**Comment by ebbit1q** [comment]
no, the script creates these json files, instead of making the files, don't make the files
