### ISSUE TITLE
Spoiler files are not deleted after release date and availability at mtgjson

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#271]
As seen in the last deployment run after the spoiler season ended, individual set files (both xml and json) got deleted and spoilers disabled (=delete `SpoilerSeasonEnabled` file) to let the Cockatrice clients know: https://github.com/Cockatrice/Magic-Spoiler/runs/2415598288?check_suite_focus=true#step:6:12
![Untitled](https://user-images.githubusercontent.com/9874850/116697486-86c97a80-a9c3-11eb-8dac-bf36a28a7342.png)

This is the resulting deployment commit to the files output branch in our repo: https://github.com/Cockatrice/Magic-Spoiler/commit/99284ba71c506e225462e563d6b8087ca98bfbed
The files branch still had both `spoiler.xml/json` files left when taking a look after the deployment: https://github.com/Cockatrice/Magic-Spoiler/tree/99284ba71c506e225462e563d6b8087ca98bfbed

It probably makes more sense to clear them or delete them as well to not run into problems or still distribute potential outdated data when the official one is there and MTGJSON took over.

For archive reasons, the CI could publish them as a release if we like. We used to do that manually at one point.

**Comment by tooomm** [comment]
Still observable with e.g. the latest switch from AFC/AFR to J21:

https://github.com/Cockatrice/Magic-Spoiler/runs/3139449304?check_suite_focus=true#step:7:12
Deploy commit with diff (https://github.com/Cockatrice/Magic-Spoiler/commit/6583fd1fa2099dec2781cd94e2ce8e5084bebffc) --> Files branch after deployment (https://github.com/Cockatrice/Magic-Spoiler/tree/6583fd1fa2099dec2781cd94e2ce8e5084bebffc)

Following with the next spoiler set being commited, spoilerseason being enabled again (create file) and the old, still existing spoiler.xml file being overwritten with the new data:
https://github.com/Cockatrice/Magic-Spoiler/runs/3167083286?check_suite_focus=true#step:7:12
Deploy commit with diff (https://github.com/Cockatrice/Magic-Spoiler/commit/4a758d8962e4467ad83f69b95849a26d901b9bb0) --> Files branch after deployment (https://github.com/Cockatrice/Magic-Spoiler/tree/4a758d8962e4467ad83f69b95849a26d901b9bb0)

**Comment by tooomm** [comment]
Apparently, individual sets are no longer deleted as well: See https://github.com/Cockatrice/Magic-Spoiler/tree/43fd33c70353bfa711f728789ece42d5c9ea8dd6
NEO released over 2 weeks ago.

**Comment by tooomm** [comment]
Looking at the [files branch today](https://github.com/Cockatrice/Magic-Spoiler/tree/efe74e84642da64375d4d3c361d890dcd9a17c7a), there are many super old xml files of individual sets piling up there that have been released several months ago.

The above mentioned `NEO` is also among them.

**Comment by ebbit1q** [comment]
fixed by 4692b62
