### ISSUE TITLE
`SPOILER_MARK` only applied to spoiler.xml, not individual {set}.xml files

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#275]
Feature got introduced in https://github.com/Cockatrice/Magic-Spoiler/commit/31ba735d95296e7754f320478b62d7a5628c6f12

The user will run in the same pic problem the above commit tried to fix, when he manually adds one of our individual spoiler files of a certain set instead pulling the "big and very crowded with promo and art sets" complete spoiler file.

<br>

Both files at the same commit:
https://github.com/Cockatrice/Magic-Spoiler/blob/7771ff6747f8c6b3ef6aaa10d70eb87cad140519/spoiler.xml#L28

https://github.com/Cockatrice/Magic-Spoiler/blob/7771ff6747f8c6b3ef6aaa10d70eb87cad140519/AFR.xml#L10

**Comment by ebbit1q** [comment]
this was my intention, if you are doing this manually I expect users to be able to manage them
