### ISSUE TITLE
Script runs into read timeouts regularly

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#281]
Can be seen in e.g. this builds from last month:
- https://github.com/Cockatrice/Magic-Spoiler/runs/3187310318?check_suite_focus=true
- https://github.com/Cockatrice/Magic-Spoiler/runs/3106864155?check_suite_focus=true
- https://github.com/Cockatrice/Magic-Spoiler/runs/3099549147?check_suite_focus=true
- https://github.com/Cockatrice/Magic-Spoiler/runs/3049472165?check_suite_focus=true
- https://github.com/Cockatrice/Magic-Spoiler/runs/2957762376?check_suite_focus=true
- https://github.com/Cockatrice/Magic-Spoiler/runs/2923092556?check_suite_focus=true

<br>

This run had a JSON decode error:
- https://github.com/Cockatrice/Magic-Spoiler/runs/3038916757?check_suite_focus=true

**Comment by ebbit1q** [comment]
these are caused by scryfall being unavailable for some reason, the best workaround for this is already implemented, running the job again later on a timer...

**Comment by tooomm** [comment]
Any idea about the JSON decode error?

**Comment by ebbit1q** [comment]
a disconnect during the download

**Comment by tooomm** [comment]
We are good here then 👍
