### ISSUE TITLE
CI: Deployment step failing when there are no changes

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#294]
I'm getting many many `Deploy workflow run failed for master branch` notifications since quite a while:

![grafik](https://user-images.githubusercontent.com/9874850/221422173-4c54e863-9db0-4926-a3f2-bd28c7909341.png)

@ebbit1q Could it be that your last CI changes are the reason? #293 
It looks like every time there are no updates, the workflow fails now?
```
no changes added to commit (use "git add" and/or "git commit -a")
Error: Process completed with exit code 1.
```

The ["No changes, not deploying" msg](https://github.com/Cockatrice/Magic-Spoiler/pull/293/files#diff-f9b2f278fa10b12db9edf49aefbb8dd890f71151e9f2d61670aa58f44bf3386aR666) is also never print to annotations, but the error:
![grafik](https://user-images.githubusercontent.com/9874850/221423182-445c2a93-5cc4-4736-a899-cfc6fae6c744.png)

Shouldn't the [deploy step be skipped](https://github.com/Cockatrice/Magic-Spoiler/pull/293/files#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3R68) completely when there are no changes?

Looking in the script logs, there seems to always be changes to the json files, while not for the spoiler.xml in the failing runs:
- sucessful run
    ```
    No new data in YONE.xml, skipping replacement
    Changes detected, replacing YONE.json with updated version
    Changes detected, replacing spoiler.xml with updated version
    Changes detected, replacing spoiler.json with updated version
    ```

- failing run:
    ```
    No new data in YONE.xml, skipping replacement
    Changes detected, replacing YONE.json with updated version
    No new data in spoiler.xml, skipping replacement
    Changes detected, replacing spoiler.json with updated version
    ```

**Comment by ebbit1q** [comment]
fixed

**Comment by tooomm** [comment]
Looking at the two failing `Deploy` runs surrounding your change... I don't think the situation changed?

**Comment by ebbit1q** [comment]
the json files have been missing from our deploys, so have xml files not been removed anymore, these should now be fixed and the action should run as expected again.

**Comment by tooomm** [comment]
> the json files have been missing from our deploys

That was on purpose, and you even suggested it. :)
https://github.com/Cockatrice/Magic-Spoiler/issues/262#issuecomment-1030942779

**Comment by ebbit1q** [comment]
I completely forgot about that, anyway, it causes this error as it'll notice a change in the json files then not add them to the list of things to deploy, which causes an empty commit.

now this error can be safely ignored, to remove the json files without triggering it we should stop the json files being different from triggering a deploy in the python script.

this did highlight a mistake in that pr though, not quoting the *.xml meant that they would never get removed, so old spoilers have been up for this entire year (only the separate xmls, so noone using the combined xml would have noticed), it's good that's fixed now.

**Comment by tooomm** [comment]
Happy to not see those errors for now 😄



>this did highlight a mistake in that pr though, not quoting the *.xml meant that they would never get removed, so old spoilers have been up for this entire year (only the separate xmls, so noone using the combined xml would have noticed), it's good that's fixed now.

Yep, a lot of old files got now deleted: https://github.com/Cockatrice/Magic-Spoiler/commit/ab3ee1e7e5adc58556e0b02b0d888c651d834c10

Problem was reported in https://github.com/Cockatrice/Magic-Spoiler/issues/271.

**Comment by tooomm** [comment]
@ebbit1q Would it actually solve our issue if we just add `*.json` to the `.gitignore` file?

**Comment by ebbit1q** [comment]
not at all, that'd be the same as it is was before 4692b62.

the issue is that the script checks for changes in the files, if the file wasn't there then creating the file is a change, this is done in python. if we don't want the json files we should remove them from the script. (they were only there for validation)
