### ISSUE TITLE
Filter certain set types out (e.g. Promo)

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#302]
**Is your feature request related to a problem? Please describe.**
Not all set types are always relevant.
The resulting xml can be quite big and yield not needed data.

**Describe the solution you'd like**
Filter out based on a defined list of set types.

**Comment by ebbit1q** [comment]
some people might be interested in a promo version though

**Comment by tooomm** [comment]
That is totally fine. In my proposed solution, the script does allow for easy configuration of this.
Just that for our centrally run version serving all Cockatice users, we need to find a balance with having relevant cards and not annoying people with weird sets.

To your "promo" example:
Promo versions of cards are fine to have and use in a deck for example, but there is no need in having them as part of a spoiler file IMO as it's not relevant for brewing decks before a release, it's only visual. Once the set is released, it will be available for them to use anyway.
