### ISSUE TITLE
Create gh-pages (github pages) Website

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Magic-Spoiler#40]
A gh-pages site might contain the total number of spoiled cards, a list of spoiled cards, most recent update date/time, and link to issues for reporting card errors.

It should also have instructions for installing a custom XML file in Cockatrice.

**Comment by tooomm** [comment]
Travis should be able to update the page automatically on run and hopefully can post which cards got added the last time (of no got added, don't change).

The page can life in this same repo just on a dedicated `gh-pages` branch.
Should the design match cockatrice.github.io? (also link to chat etc.?)

**Comment by tooomm** [comment]
I don't see that happen any time soon as it's quite a bigger project and it might just not be needed.

Scryfall has very nice overviews of cards and orders them in spoiler season per spoiled date, too!

>It should also have instructions for installing a custom XML file in Cockatrice.

Spoilers have been automatically integrated in between as well
