### ISSUE TITLE
include build date in files

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#54]
date + time + timezone info of creation at the start/top of xml and json files

**Comment by dev-id** [comment]
I don't have a problem with doing this for XML, but it *might* cause an XSD/xmllint check ( #50 ) to fail.

Our JSON format doesn't really have a means for this.

**Comment by tooomm** [comment]
There is an issues open for the same over on trice - so the XSD should see an update at one point as well.
It's outdated and not correct at the moment anyway.

**Comment by leematos** [comment]
XML/json comments should be ignored by any validations, yeah?

```
<?ignore This is an an XML comment showing the file was generated at 00:00:00 AM 00/00/00 ?>
```

```
// I suspect this will work for json above the object literal, but we'd have to try
```

**Comment by dev-id** [comment]
>// I suspect this will work for json above the object literal, but we'd have to try

This is not supported by the JSON standard, but it's widely used. We had to bring in a special library for python because the built in `json` did not handle comments.

**Comment by leematos** [comment]
I also had the epiphany that we could just make the filename HOU.00-00-00.xml?

**Comment by tooomm** [comment]
It could be `HOU_spoiler_yyyy-mm-dd.xml` and `spoiler_yyyy-mm-dd.xml`.
The format with just two digits for year can always be a bit misleading.

**But this will make the link to the file not static anymore!**
So I guess this is something once we use github releases since the api can just be queried and will return the correct file name. Right now with the `files` branch that seems not to be ideal.
