### ISSUE TITLE
Current spoilers

### ISSUE THREAD

**Issue by Thunderbeliever** [Cockatrice/Magic-Spoiler#61]
For the Xml for Hours of devastation is there a xml with ONLY hours? I was told it included the Ixalan and the commander 17 stuff, why not break these up? what is the point of Ixalan cards now they are not legal for another 6 months roughly

**Comment by dev-id** [comment]
You can find the Hours only file on our files branch here: https://github.com/Cockatrice/Magic-Spoiler/tree/files

Specifically, https://github.com/Cockatrice/Magic-Spoiler/blob/files/HOU.xml (click `Raw` for downloadable version)

We try to include any legitimate spoiled card. You can also turn off the sets you don't want yet in your Set List in Cockatrice.
