### ISSUE TITLE
create changelog

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#72]
We print the newly build .xml to the log, so travis has that...
Can't we pull the most recent one from files branch and compare them to just print the lines that are actually different?

Lowers down the log lines by a lot (we can use that sleep 5 recommendation as well), and it's more useful because you can easily check what really changed in this run instead having to search the log for changes to that one file that you fixed for example. You still miss out on any other changes as long as there is no file upload and diff to check. (Errors are just one thing)

With that said... that info is basically a changelog ( `<!--- CHANGELOG --->` print yeah) and can be uploaded to the files branch as well (changelog.json) to be linked to from pages or within the xml file itself, it might be useful for updating the releases description or a future github page etc.

**Comment by dev-id** [comment]
The 'hacky' way is to paste the new data to the file on the files branch of your fork.

**Comment by tooomm** [comment]
New idea...

We can tell travis in `after_deploy` or `after_script` step, right AFTER travis pushed the changes to the files branch, that it should check the diff on the new spoiler.xml output and build something from there...
Instead comparing the old and the new created output files on it's own.
Could result in a new changelog file and a second push for example.

**Comment by tooomm** [comment]
No longer valid
