### ISSUE TITLE
Better non-existent card handling

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Magic-Spoiler#74]
A few bad cards made it through to the very end:

https://github.com/Cockatrice/Magic-Spoiler/commit/cebc4ffd459e2e3b26f260691a199edf4a401aa8
https://github.com/Cockatrice/Magic-Spoiler/commit/86bfa1f0de780e5fb5005a01d75a2ad7e07ef89a

**Comment by tooomm** [comment]
In case the rss feed has bad data mtgs remove them from the site, but not from the feed.
There are no updates or corrections applied to the feed either.

Possible solution could be to check the site to verify the spoilers are still valid.
