### ISSUE TITLE
All open parentheses are missing from reminder texts

### ISSUE THREAD

**Issue by Cheldra** [Cockatrice/Magic-Spoiler#81]
E.g. [Proven Combatant](http://www.mtgsalvation.com/cards/hour-of-devastation/28984-proven-combatant)'s text is: 

>Eternalize {4}{U}{U} {4}{U}{U}, Exile this card from your graveyard: Create a token that's a copy of it, except it's a 4/4 black Zombie Human Warrior with no mana cost. Eternalize only as a sorcery.**)**

Note the missing `(` before the second Eternalize cost.

Not sure what's causing this.

**Comment by tooomm** [comment]
It correctly exist in the mtgs feed:

>Rules Text: Eternalize {4}{U}{U} **(**{4}{U}{U}, Exile this card from your graveyard: Create a token that's a copy of it, except it's a 4/4 black Zombie Human Warrior with no mana cost. Eternalize only as a sorcery.)


```
    <item>
      <guid isPermaLink="false">28984</guid>
      <link>http://www.mtgsalvation.com/cards/hour-of-devastation/28984-proven-combatant</link>
      <title>Proven Combatant</title>
      <description>

&lt;b&gt;Name:&lt;/b&gt; &lt;b&gt;Proven Combatant&lt;/b&gt;&lt;br&gt;
Set: Hour of Devastation&lt;br&gt;
Cost: U&lt;br&gt;
Type: Creature - Human Warrior&lt;br&gt;

Pow/Tgh: 1/1&lt;br&gt;

Rules Text: Eternalize {4}{U}{U} &lt;i&gt;({4}{U}{U}, Exile this card from your graveyard: Create a token that's a copy of it, except it's a 4/4 black Zombie Human Warrior with no mana cost. Eternalize only as a sorcery.) &lt;/i&gt;&lt;br&gt;

Flavor Text: "It's not wise to keep glory waiting."&lt;br&gt;

Illus. Clint Cearly&lt;br&gt;
Rarity: Common&lt;br&gt;
Set Number: #42/199&lt;br&gt;
&lt;br&gt;</description>
      <pubDate>Fri, 23 Jun 2017 15:40:56 Z</pubDate>
      <a10:updated>2017-06-23T15:40:56Z</a10:updated>
    </item>
```

<br>

**Edit:** this is actually an older issue... appeared as well for AKH with former script
https://github.com/tritoch/SpoilerSeason/blob/files/AKH.xml#L1959

**Comment by leematos** [comment]
I suspect it's something to do with our regex here: https://github.com/Cockatrice/Magic-Spoiler/blob/master/spoilers.py#L39
