### ISSUE TITLE
differences between spoiler.xml and set.xml

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#83]
See https://github.com/Cockatrice/Magic-Spoiler/compare/8cd39606367e...586aae5d1c4f

The ordering of values is different

**Comment by leematos** [comment]
Can you help me understand what each is for and how they should be the same and how they should be different?

**Comment by tooomm** [comment]
The general spoiler files (both xml and json) contain all available spoilers, even from different sets. (different to the specific set files like hou.xml or hou.json)

xml is formatted in Cockatrice style to use it directly in the app
json is formatted in mtgjson style for other projects to use it
They have some different fields and key names for example.

I just realized in the linked diff that the ordering is different for the two xml files. Which shouldn't be the case:
- set.xml (here hou.xml):
`rarity` `picURL` `HOU`

`<set rarity="Uncommon" picURL="http://media.wizards.com/2017/hou/en_pneaNXiy6c.png">HOU</set>`
- spoiler.xml:
`picURL` `rarity` `HOU`

`<set picURL="http://media.wizards.com/2017/hou/en_pneaNXiy6c.png" rarity="Uncommon">HOU</set>`

**Comment by leematos** [comment]
I haven't looked at the code yet, but do they both use the same function to build the XML file?

**Comment by dev-id** [comment]
`spoiler.xml` is passed through the pretty_xml function which re-orders attributes (alphabetically?)

https://github.com/Cockatrice/Magic-Spoiler/blob/4e43b90156b5ff31ff273ba8afb5aeef3859f6eb/spoilers.py#L1221-L1224

The individual files can be passed through the same function.
