### ISSUE TITLE
Cards Missing from xml

### ISSUE THREAD

**Issue by Thunderbeliever** [Cockatrice/Magic-Spoiler#86]
Cards that were reprinted are not listed with the Hour cards. Also the 3 Gods of Hours are not listed with the Hour cards but you have to hunt to find them.

**Comment by tooomm** [comment]
I can't follow you. :)

Can you provide some more details and names of cards that are missing for example?

**Comment by Thunderbeliever** [comment]
Well it could be an issue with Dr4ft.com but i just did a draft where i had Manalith and Unsummon but instead of being sorted into their respective places on my deck list they were chucked into "unknown" section.  
The Gods of Hours, Scorpion, locust, and Scarab are in with the invocation and not listed with the Actual set.
I have other isues about the Dr4ft.com site, but ill take those to Tritoch myself as i do not see a place to post them.

**Comment by tooomm** [comment]
>I have other isues about the Dr4ft.com site, but ill take those to Tritoch myself as i do not see a place to post them.

---> https://github.com/dr4fters/dr4ft
<br>

>Well it could be an issue with Dr4ft.com but i just did a draft where i had Manalith and Unsummon but instead of being sorted into their respective places on my deck list they were chucked into "unknown" section.

"The places on my deck list"? I guess you're speaking about the your deck after importing the file from dr4ft to Cockatrice? Or on dr4ft itself if you order your cards there?
If you have a look into the actual [hou spoiler xml file](https://github.com/Cockatrice/Magic-Spoiler/blob/files/HOU.xml) which you are using for Cockatrice too (and hopefully updating from time to time) you can search for this cards.
Both of them are correctly tagged as "Artifact" and "Instant". So i guess you use an older version of the file. In the nature of how spoiler work and that they have errors we have to update and correct it all the time.

This version now is pretty complete though. So just replace the one you're using in Cockatrice and you should be fine.
We try to include some more info about the file in the future to make it easier to know if there is a updated version available --> https://github.com/Cockatrice/Magic-Spoiler/issues/54

>The Gods of Hours, Scorpion, locust, and Scarab are in with the invocation and not listed with the Actual set.

They are also in the linked xml file. :)

<br>
Thanks for letting us know. Without people like you that inform us about errors or missing cards we can't
provide a quality file for everybody within a reasonable time! So keep up reporting please. ;)

**Comment by Thunderbeliever** [comment]
No problem. thats why i report. I have the most up to date cockatrice i just noticed that when i uploaded my deck to cockatrice that both cards were not listed in their normal spots. its not a HUGE OMG issue but it is something wrong. thx for quick answers.

**Comment by tooomm** [comment]
So your issue persists? Then don't close it, haha.

You might have the most up to date Cockatrice... but you might not have the most up-to-date spoiler file loaded into Cockatrice!

Check this:
- download the file found here: https://raw.githubusercontent.com/Cockatrice/Magic-Spoiler/files/HOU.xml
- save as `HOU spoiler.xml` or any other suitable name
- in Cockatrice go to `Card Database --> Open custom sets folder`
- there delete all old custom spoiler sets and copy/move the newly downloaded file to that location
(or use `Card Database --> Add custom sets/cards`, you still have to delete old ones first!)


It's the same with your normal card database. You have to update manually to have all the new cards available! [How to update my card database](https://github.com/Cockatrice/Cockatrice/wiki/Frequently-Asked-Questions#how-do-i-update-my-card-database-to-have-the-latest-cards)

**Comment by Thunderbeliever** [comment]
I have the set updated and it seemed more like a dr4ft.com issue after you explained it so i closed it because it was not related to cockatrice persay. I am assuming they were mislabeled on the dr4ft.com side. I know i have the correct spoiler as Tritoch himself had to help me get the dang thing to work, lol

**Comment by tooomm** [comment]
When did he help you get the file to work?

**Comment by Thunderbeliever** [comment]
Yesterday, and he just contacted me via cockatrice and we worked out the
issues, they were on the Dr4ft.com side of things

**Comment by tooomm** [comment]
Great, so dr4ft can fix that.

<br>

For general reference...

A list of projects related to the Cockatrice application:
Cockatrice app --> https://github.com/Cockatrice/Cockatrice
Tokens --> https://github.com/Cockatrice/Magic-Token
Spoiler (here) --> https://github.com/Cockatrice/Magic-Spoiler
Webpage: https://github.com/Cockatrice/cockatrice.github.io

other projects like dr4ft --> https://github.com/dr4fters/dr4ft
