### ISSUE TITLE
mark set in spoiler file as spoiler

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#87]
The "set name long" could be `Hour of Devastation (Spoiler)` for example.

So that people can see and realize in the "Edit sets" dialog what they are dealing with.
Once mtgjson updates and we remove the set from spoiler it should be a smooth transition.

**Comment by dev-id** [comment]
If Cockatrice requests this, we can do it. I'd rather have them handle it.

**Comment by tooomm** [comment]
I like that approach too!
All set imports from file=spoiler.xml show a extension/tag. Not bad.

**Comment by tooomm** [comment]
I altered a `spoiler.xml` file for testing a bit:
```
	<sets>		
		<set>			
			<name>DOM (Spoiler)</name>			
			<longname>Dominaria (Spoiler)</longname>			
			<settype>Expansion</settype>			
			<releasedate>2018-04-27</releasedate>			
		</set>		
	</sets>
	<cards>	
...
```

The result is appealing to me and looks like that:
- First run after file change:
![first-run](https://user-images.githubusercontent.com/9874850/34921669-e6faef34-f985-11e7-936f-5e114761fa19.png)

- `Edit sets...` dialog:
![edit-sets](https://user-images.githubusercontent.com/9874850/34921691-1639ac90-f986-11e7-820e-57fe2e4942ad.png)

<br>

@ZeldaZach How do you feel about a solution on Cockatrice side as @dev-id suggested?
Like "All set imports from file=spoiler.xml show a extension/tag." in `Edit sets...`?

**Comment by tooomm** [comment]
@ebbit1q you achieved something similar with https://github.com/Cockatrice/Magic-Spoiler/commit/31ba735d95296e7754f320478b62d7a5628c6f12 and https://github.com/Cockatrice/Magic-Spoiler/pull/273 while fixing spoiler card art.

IMO `AFR (Spoiler)` looks not only more pleasing than `AFR~` in client and in the pictures folder, it also explains better to the user what's going on. He can even find old spoiler pic folders quicker and more convenient in order to clean them up.

Compare the screen above to this... quite confusing with the normal + spoiler type of the same set and finding them in the first place:
![spoiler](https://user-images.githubusercontent.com/9874850/125793210-da6d9ec9-fab6-41cc-84f3-1ae1638258d7.png)

I happily PR an update to `SPOILER_MARK` if you don't have any strong and obvious hesitations. 👍
Spaces on linux should not be a deal breaker nowadays? :)

**Comment by ebbit1q** [comment]
we keep the spoiler code short because it's a code not a full name, adding this to the set name makes sense though

**Comment by tooomm** [comment]
>we keep the spoiler code short because it's a code not a full name, **adding this to the set name makes sense though**

It's not my preferred solution (Reasons like "longname" not being shown in certain dialogs and generally worse visibility are shown in the pics in https://github.com/Cockatrice/Magic-Spoiler/issues/87#issuecomment-357646599), but it's an improvement for users nonetheless.

Either way, users can then search for "spoiler" as well which is good. 👍
