### ISSUE TITLE
Dependent Corrections

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Magic-Spoiler#88]
Currently, if a field is corrected and other fields that depend on it, those fields will not get updated if they were generated programatically.

Fixing `type` does not fix `types`. It may not error for all the dependent fields for that `type` also, such as loyalty for planeswalkers or p/t for creatures.

Other examples off the top:
colors, and colorIdentity, and cmc are dependent sometimes on manaCost and sometimes on each other

**Comment by tooomm** [comment]
That's a devils circle. :)

If we apply corrections at the end (as we do now) we still use the wrong values to generate other fields like cmc earlier.
If we apply corrections before the generations we can't fix wrong generations.

The second seems controllable though?
We just changed it recently I think? Can you recall why?

**Comment by leematos** [comment]
I'm not clear enough in the code yet, but I'm thinking:

+ We get the data from our trusted source
+ We apply any known corrections
+ We generate dependent values
+ We generate output file

I _think_ that order keeps us from generating wrong values.

**Comment by dev-id** [comment]
As long as we don't overwrite any *correct* data in step `Generate dependent values` that will work. WOTC likes to throw us curveballs, and whatever dependents we write will *someday* (knowing wotc, in the very next set) be incorrect. I think the last step needs to be applying corrections (even if just a second pass) to ensure that if we have a correction to a dependent value, it isn't overwritten in step 3. That or exempt anything from corrections when generating dependents. (e.g. if `cmc` is corrected to 0, don't let `generate dependent value` overwrite it)

**Comment by leematos** [comment]
> whatever dependents we write will someday (knowing wotc, in the very next set) be incorrect.

Agreed, I suspect this part of the code could change often.

> (e.g. if cmc is corrected to 0, don't let generate dependent value overwrite it)

In that example if generate dependent value overwrote the cmc, that would mean our correction wasn't correct :P

as a unit test, I think it's worthwhile to make sure that the code isn't overwriting in that way, but if we generate corrections correctly (we need to figure that out) it should be a one way translation and generating dependent values should never overwrite an independent variable we defined by nature of being dependent :)
