### ISSUE TITLE
refactor verify_files call

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#90]
>It also looks like verify_files.py could be refactored based on this as well? I'm not sure what the end game is for that file.

>main.py should call verify_files.py that would be better.

See https://github.com/Cockatrice/Magic-Spoiler/pull/77#issuecomment-312499149

**Comment by leematos** [comment]
Can you assign this to me? Happy to tackle it :)

**Comment by dev-id** [comment]
Fixed by #99
