### ISSUE TITLE
rethink travis notification

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#93]
I feel like we trigger *a lot* of activity notifications in Gitter. Not all of them very useful.

Right now we use the defaults:
```
on_success: always
on_failure: always
on_start: always
```

Maybe we should lower the amount of notifications for gitter in travis.yml!
`options: [always|never|change] default: always`

Go with **change, change, never** instead? (as I've no idea what change on `on_start` would do...)
That's what we use on Cockatrice as well: https://github.com/Cockatrice/Cockatrice/blob/master/.travis.yml#L22-L27

Documentation was not too helpful, no examples: https://docs.travis-ci.com/user/notifications

<br>

This issue is for discussion and a reminder to look into it at one point.

**Comment by leematos** [comment]
I think that disabling on_start makes sense. That's effectively line spam for our purposes.

**Comment by tooomm** [comment]
Especially with our short run time now after #101 it feels even more unnecessary to have a notification on start and one minute later for fail/success.
The container based builds also start immediately, so no need to wait 10min in a cue in which case the start notification would be helpful.
