### ISSUE TITLE
modularise and break up code

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#95]
- [x] Break up spoiler.py into independent modules (#98)
- [ ] Make sure each module has no weird cross dependencies
- [ ] Making sure each modules state is properly isolated and that modules pass consistent values out.
- [ ] Writing tests for modules to make sure that when we make changes, that we get the expected result on the other side. :)

Taken from: https://github.com/Cockatrice/Magic-Spoiler/pull/98#issuecomment-313128570

---

*old issue text:*

>- Break spoiler.py up into a few modules (mtgs/scryfall/etc)
>- Better manageable, read and maintain
>
><br>
>
>Also consider separate "mtgs_transformations/corrections.json" (https://github.com/Cockatrice/Magic-Spoiler/blob/4e43b90156b5ff31ff273ba8afb5aeef3859f6eb/spoilers.py#L88-L104)
>- More robust core application
>- Split essentials (process modifications) from actual data modifications 
>- Easier to contribute for non-programmers
>
>Basic workflow could be:
>Get+scrape data (one for each service?) -> correct errors -> bake cards -> build release files
>
>Conversation regarding that on Gitter:  :point_up: [July 3, 2017 3:51 PM](https://gitter.im/Cockatrice/Magic-Spoiler?at=595a4bc8329651f46e4adf15)

**Comment by tooomm** [comment]
Reopened to keep track of the next steps you mentioned @leematos

**Comment by dev-id** [comment]
Masterpieces are currently scraped from MTGS, should go in mtgs_scraper

**Comment by tooomm** [comment]
@leematos did you have time to look into that process any further? 👋
