### ISSUE TITLE
use requests over urllib

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#96]
allows to drop `urllib` library

https://github.com/Cockatrice/Magic-Spoiler/blob/master/spoilers.py#L692-L704
https://github.com/Cockatrice/Magic-Spoiler/blob/master/spoilers.py#L1302-L1310

Thanks for the input @leematos :point_up: [July 1, 2017 5:16 AM](https://gitter.im/Cockatrice/Magic-Spoiler?at=5957141ca42fa68a30898f15)

**Comment by leematos** [comment]
I'll fix this once https://github.com/Cockatrice/Magic-Spoiler/pull/98 makes it in.
