### ISSUE TITLE
Create 'spoiler season' dates file

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Magic-Spoiler#97]
Create an input file that contains lists of start/end of official spoiler season, for modifying the [spoilerStatus.txt](https://github.com/Cockatrice/Magic-Spoiler/blob/files/spoilerStatus.txt) file. Should enable when first spoils start rolling in OR season starts & set is in set_infos. Disable at end of season or when mtgjson updates.

**Comment by tooomm** [comment]
The actual approach for spoiler compatibility/support is getting quite complex... :D
I'm still all in for the Oracle way and think that might even be the cleanest and easiest for the user (and us?).

**Comment by dev-id** [comment]
Take it up with [Big Sister!](https://github.com/Cockatrice/Cockatrice/issues) Date files might help us in other ways.

**Comment by tooomm** [comment]
potential source: http://www.mtgsalvation.com/forums/magic-fundamentals/the-rumor-mill/673776-schedule-of-upcoming-releases-and-spoiler-seasons
